name: UselesslyHardcoded
version: '${project.version}'
main: adhdmc.uselesslyhardcoded.UselesslyHardcoded
api-version: 1.19
description: for the Messages to print to the user
commands:
  rules:
    description: rules
    aliases: [rule , info]
  claimkit:
    description: claim kit
    aliases: [kitclaim, shovel, goldshovel, goldenshovel]
  vote:
    description: vote
    aliases: [voteall, voting , votes]
  livemap:
    description: map link
    aliases: [dynmap]
  yeet:
    description: yeet
  fly:
    description: fly
    permission: uhc.fly
  flyspeed:
    description: flyspeed
    permission: uhc.flyspeed
  walkspeed:
    description: walkspeed
    permission: uhc.walkspeed
  rename:
    description: rename
    permission: uhc.rename
permissions:
  uhc.fly:
    description: fly
    default: op
  uhc.flyspeed:
    description: flyspeed
    default: op
  uhc.walkspeed:
    description: walkspeed
    default: op
  uhc.rename:
    description: rename
    default: op